// Helpers for animating aircraft along their routes from the flight_times.json
// schedule sidecar (generated by src/web_animation.py via src.export_web).

export type FlightTimes = Map<string, { takeoff: number; landing: number }>;

// flight_key -> [takeoffISO, landingISO]
type FlightTimesJson = Record<string, [string, string]>;

export async function loadFlightTimes(
  snapshot: string
): Promise<FlightTimes | null> {
  let res: Response;
  try {
    res = await fetch(`/data/${snapshot}/flight_times.json`);
  } catch {
    return null;
  }
  if (!res.ok) return null;

  const json = (await res.json()) as FlightTimesJson;
  const map: FlightTimes = new Map();
  for (const key in json) {
    const [t, l] = json[key];
    const takeoff = Date.parse(t);
    const landing = Date.parse(l);
    if (!Number.isNaN(takeoff) && !Number.isNaN(landing) && landing > takeoff) {
      map.set(key, { takeoff, landing });
    }
  }
  return map;
}

// Per-flight weather exposure: flight_key -> a string of one char per weather
// frame ("1" = flying through dangerous convective weather at that frame).
export type FlightExposure = Map<string, string>;

export async function loadFlightExposure(
  snapshot: string,
  scenario: "baseline" | "recommended"
): Promise<FlightExposure | null> {
  let res: Response;
  try {
    res = await fetch(`/data/${snapshot}/flight_weather_${scenario}.json`);
  } catch {
    return null;
  }
  if (!res.ok) return null;
  const json = (await res.json()) as Record<string, string>;
  return new Map(Object.entries(json));
}

const R = 6371; // km — only ratios matter, so units are irrelevant

function haversine(a: [number, number], b: [number, number]): number {
  const toRad = Math.PI / 180;
  const dLat = (b[1] - a[1]) * toRad;
  const dLon = (b[0] - a[0]) * toRad;
  const lat1 = a[1] * toRad;
  const lat2 = b[1] * toRad;
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.min(1, Math.sqrt(h)));
}

export type PathMetrics = { cum: number[]; total: number };

// Cumulative great-circle distance at each vertex (cum[0] === 0).
export function buildPathMetrics(path: [number, number][]): PathMetrics {
  const cum = new Array(path.length).fill(0);
  for (let i = 1; i < path.length; i++) {
    cum[i] = cum[i - 1] + haversine(path[i - 1], path[i]);
  }
  return { cum, total: cum[cum.length - 1] || 0 };
}

// Position at a fraction [0,1] of the way along the path, plus the heading
// (degrees clockwise from north) of the segment the aircraft is on.
export function positionAt(
  path: [number, number][],
  metrics: PathMetrics,
  frac: number
): { position: [number, number]; bearing: number } {
  if (path.length === 1 || metrics.total === 0) {
    return { position: path[0], bearing: 0 };
  }
  const target = Math.max(0, Math.min(1, frac)) * metrics.total;
  const { cum } = metrics;

  // Find the segment [i-1, i] containing the target distance.
  let i = 1;
  while (i < cum.length - 1 && cum[i] < target) i++;

  const segStart = cum[i - 1];
  const segLen = cum[i] - segStart || 1;
  const t = (target - segStart) / segLen;
  const a = path[i - 1];
  const b = path[i];
  const position: [number, number] = [
    a[0] + (b[0] - a[0]) * t,
    a[1] + (b[1] - a[1]) * t,
  ];
  return { position, bearing: bearingDeg(a, b) };
}

// Bearing in degrees clockwise from north.
function bearingDeg(a: [number, number], b: [number, number]): number {
  const toRad = Math.PI / 180;
  const lat1 = a[1] * toRad;
  const lat2 = b[1] * toRad;
  const dLon = (b[0] - a[0]) * toRad;
  const y = Math.sin(dLon) * Math.cos(lat2);
  const x =
    Math.cos(lat1) * Math.sin(lat2) -
    Math.sin(lat1) * Math.cos(lat2) * Math.cos(dLon);
  return ((Math.atan2(y, x) * 180) / Math.PI + 360) % 360;
}
