// Loads the pre-rendered weather-radar frames (composite reflectivity, dBZ)
// for a snapshot. Frames are generated by src/web_animation.py into
// /data/<snapshot>/weather/ as transparent PNGs plus a weather.json manifest.

export type WeatherFrame = {
  index: number;
  valid_from: string; // ISO UTC instant the frame's 15-min window starts
  valid_to: string;
  url: string; // relative to /data/<snapshot>/
};

export type WeatherManifest = {
  snapshot: string;
  // BitmapLayer bounds: [west, south, east, north]
  bounds: [number, number, number, number];
  shape: [number, number];
  product: string;
  units: string;
  frames: WeatherFrame[];
};

// Loaded manifest with absolute, fetchable frame URLs.
export type LoadedWeather = {
  bounds: [number, number, number, number];
  frames: {
    index: number;
    validFrom: string;
    validTo: string;
    // Midpoint of the 15-min window — the HRRR "valid time" (clean :00/:15/...).
    // For frame 0 this equals the snapshot's ask time.
    validAt: string;
    url: string;
  }[];
};

export async function loadWeatherManifest(
  snapshot: string
): Promise<LoadedWeather | null> {
  const base = `/data/${snapshot}`;
  let res: Response;
  try {
    res = await fetch(`${base}/weather.json`);
  } catch {
    return null;
  }
  if (!res.ok) return null;

  const manifest = (await res.json()) as WeatherManifest;
  if (!manifest.frames || manifest.frames.length === 0) return null;

  return {
    bounds: manifest.bounds,
    frames: manifest.frames.map((f) => ({
      index: f.index,
      validFrom: f.valid_from,
      validTo: f.valid_to,
      validAt: new Date(
        (Date.parse(f.valid_from) + Date.parse(f.valid_to)) / 2
      ).toISOString(),
      url: `${base}/${f.url}`,
    })),
  };
}

// Kick off browser fetches/decodes for every frame so animation is flicker-free
// (deck.gl's BitmapLayer then reads each PNG straight from cache).
export function preloadWeatherFrames(frames: { url: string }[]): void {
  for (const f of frames) {
    const img = new Image();
    img.src = f.url;
  }
}
